[package]
id = dashboard_help_badge
check_for_updates = 0

[id]
version = 0.5.0
name = dashboard_help_badge

[ui]
is_visible = 1
label = Dashboard Help Badge
show_in_nav = 1

[launcher]
author = Leiter Consulting
description = Accessible, configurable contextual help elements for Dashboard Studio tiles
version = 0.5.0

[install]
is_configured = 0
build = <@- buildNumber @>

[manifest]
category = Custom
